"""Hand-curated research for the 2027-2029 draft boards (Dynasty Puck HQ).

Facts (teams, stats, birth month, size, quotes) come from the cited public sources. Style, categories (our 15
fantasy categories), ceiling, comparison and the fantasy note are Dynasty Puck HQ analysis built on those
write-ups. They're opinions and are labelled as such in the app. Update this file and re-run make_boards.py.
"""

SRC = {
    "TK": {"name": "Tankathon big board", "url": "https://www.tankathon.com/nhl/big-board", "date": "2026-09-10"},
    "DFO": {"name": "Daily Faceoff (S. Ellis) top 32", "url": "https://www.dailyfaceoff.com/news/2027-nhl-draft-rankings-top-32-july-dupont-privalov-joseph-skvortsov-meyer-scouting-reports", "date": "2026-07"},
    "THW": {"name": "The Hockey Writers (P. Baracchini) top 32", "url": "https://thehockeywriters.com/2027-nhl-draft-baracchinis-rankings-preseason-top-32/", "date": "2026-09-07"},
    "THN": {"name": "The Hockey News (T. Ferrari) tiers", "url": "https://thehockeynews.com/news/latest-news/2027-nhl-draft-ranking-pre-season-tier-list-sees-landon-dupont-alone-atop", "date": "2026-09-18"},
    "THN10": {"name": "The Hockey News projected top 10", "url": "https://thehockeynews.com/news/latest-news/2027-nhl-draft-projected-top-10-landon-dupont-alexis-joseph-and-carter-meyer-highlight-exciting-class", "date": "2026-06-28"},
    "THWH": {"name": "THW Hlinka Gretzky standouts", "url": "https://thehockeywriters.com/2027-draft-eligible-standouts-hlinka-gretzky-cup/", "date": "2026-08-09"},
}

# Daily Faceoff July top 32 (+ 'also considered' = 33+)
DFO = ["Landon DuPont", "Nazar Privalov", "Alexis Joseph", "Sergei Skvortsov", "Carter Meyer", "Sammy Nelson", "Brock England",
       "Petr Tomek", "Dima Zhilkin", "Jaxon Jacobson", "Timothy Kazda", "Luca Santala", "Max Calce", "Jonah Neuenschwander",
       "Milan Sundström", "Brock Cripps", "Yevgeni Yakunin", "Andrei Pustovoy", "Levi Harper", "Boston Tait", "Bosse Meijer",
       "Diego Gutierrez", "Vladimir Shtyrkhunov", "Nolan Fitzhenry", "Rocco Pelosi", "Ryerson Edgar", "Jamie Glance",
       "Noah Davidson", "James Scantlebury", "Kohyn Eshkawkogan", "Shaeffer Gordon-Carroll", "Douglas Johnsson"]
DFO_ALSO = ["Lenni Kokkonen", "Trevor Daley Jr.", "Lukas Kachlir", "Michal Hartl", "Roberts Naudins"]
# The Hockey Writers September top 32
THW = ["Landon DuPont", "Nazar Privalov", "Sergei Skvortsov", "Alexis Joseph", "Jonah Neuenschwander", "Carter Meyer",
       "Dima Zhilkin", "Brock England", "Sammy Nelson", "Jaxon Jacobson", "Brock Cripps", "Milan Sundström", "Andrei Pustovoy",
       "Luca Santala", "Jaakko Wycisk", "Bosse Meijer", "Kayden Stroeder", "Timothy Kazda", "Kohyn Eshkawkogan", "Levi Harper",
       "Gavin Burcar", "Boston Tait", "Yevgeni Yakunin", "Malik L'Italien", "Tomas Selic", "Noah Davidson",
       "Vladimir Shtyrkhunov", "Dorian Eklund Aspe", "Lukas Kachlir", "Roberts Naudins", "Ryerson Edgar", "Johnny McLaughlin"]
# The Hockey News September tiers (order within a tier doesn't matter)
THN_TIERS = {1: ["Landon DuPont"], 2: ["Sergei Skvortsov", "Nazar Privalov", "Carter Meyer", "Dima Zhilkin"],
             3: ["Jonah Neuenschwander", "Brock England", "Milan Sundström", "Bosse Meijer", "Sammy Nelson"],
             4: ["Brock Cripps", "Malik L'Italien", "Kohyn Eshkawkogan", "Alexis Joseph", "Jaakko Wycisk", "Petr Tomek", "Douglas Johnsson"]}

# name -> (style, cats, ceiling, comp, note, tags)
A27 = {
    "Landon DuPont": ("Elite puck-moving D / PP quarterback", ["Pt-D", "A", "STP", "Cor"], "Franchise No. 1 D",
                      "", "Former WHL exceptional-status D who jumped from 60 to 73 points and won the WHL title, now at Michigan. Every source has him No. 1. He runs a power play, blocks shots and competes. The dream fantasy D: elite Pt-D and STP with strong Corsi.", ["consensus #1", "NCAA"]),
    "Nazar Privalov": ("Power forward, shooter-playmaker", ["G", "SOG", "Hit", "PIM"], "1st-line power C/W",
                       "Malkin (THW)", "6'4\" 227 lb MHL rookie of the year (30 goals). Physical and skilled, a rare banger with a scorer's touch. That's a perfect fit for our Hit/PIM + G/SOG mix. The KHL contract could delay his arrival.", ["KHL contract", "power forward"]),
    "Alexis Joseph": ("6'5\" all-situations power C", ["G", "SOG", "Hit", "2G+A"], "1st/2nd-line power C",
                      "", "60 points as a QMJHL rookie, plus 13 in 5 games at the U17 World Challenge. Big-body net-front scorer with physicality. The skating isn't explosive, but he projects for category volume (SOG, Hit, goals).", ["power forward"]),
    "Sergei Skvortsov": ("Skilled two-way winger, high hockey IQ", ["A", "G", "Tk", "Cor"], "1st-line winger",
                         "", "43 points in 52 MHL games, and he scored his first KHL goal at 17 in September 2026. Elite hands and reads, relentless motor. Needs to add strength. Projects as a points-and-possession winger.", ["KHL"]),
    "Carter Meyer": ("Physical two-way C, heavy shot", ["Hit", "G", "SOG", "Tk"], "2nd-line two-way C",
                     "MacKinnon-inspired (THN feature)", "Left the NTDP for the QMJHL's Quebec Remparts, with Boston University expected in 2028-29. He hits everything and has a wicked release. A rare multi-category forward (Hit + G + Tk).", ["multi-cat"]),
    "Sammy Nelson": ("Play-driving dual-threat F", ["A", "G", "SOG", "Cor"], "2nd-line F",
                     "", "54 points in 58 games for the NTDP; missed the 2026 cutoff by four days. Now at Notre Dame. High shot generator with strong details, so good SOG and Corsi.", ["NCAA", "late birthday"]),
    "Brock England": ("Speed C, shooter-playmaker", ["G", "A", "SOG", "Tk"], "2nd-line C",
                      "", "20+ goals and 50+ points as a WHL rookie. The best skater among his peers (THW), with two goals in the Hlinka final. Turnover-forcing speed suggests Tk upside.", []),
    "Petr Tomek": ("Smart two-way C (pro experience)", ["A", "Tk", "Cor"], "Middle-six C",
                   "", "20 points in 51 games in Czechia's top league at 16; the other seven Czech D-1 players combined for one point. Excellent skater and thinker. A floor-first profile.", ["pro league"]),
    "Dima Zhilkin": ("Agitator-scorer (\"next superpest\")", ["PIM", "Hit", "G", "A"], "1st-line agitator W",
                     "Superpest archetype (THN)", "75 points and 100 PIM as Saginaw's 17-year-old captain, and dominated the U18 Worlds. PIM + Hit + points is gold in our format, so a fantasy riser.", ["fantasy riser", "PIM"]),
    "Jaxon Jacobson": ("Undersized elite playmaking C", ["A", "STP", "2G+A"], "2nd-line playmaker",
                       "", "85 points (60 assists) in 63 WHL games; missed the 2026 cutoff by three months. Assist machine who could anchor a PP.", ["late birthday"]),
    "Timothy Kazda": ("1-on-1 skill winger", ["G", "A", "SOG"], "2nd-line W",
                      "", "41 points in 59 USHL games, and tied for the U18 Worlds scoring lead with 12 points. Moved to the OHL's Guelph Storm. Dangerous skill, mostly offense.", []),
    "Luca Santala": ("Shooter with vision", ["G", "SOG", "A"], "2nd-line scoring W",
                     "", "Nearly a goal per game internationally for Finland U18, now with the OHL's London Knights. Excellent shot, not physical.", []),
    "Max Calce": ("Energetic skilled C (formerly Max Penkin)", ["G", "A", "SOG"], "Middle-six C",
                  "", "Top young German forward, already playing DEL minutes with Mannheim.", ["pro league"]),
    "Jonah Neuenschwander": ("Big two-way power C", ["G", "SOG", "Hit", "Cor"], "2nd-line power C",
                             "", "Swiss World Junior player at 15. 12 points in 32 NL games is the best by a Swiss draft-1 player in 60 years. Dominant at the Hlinka. Size + shot suits category leagues.", ["pro league", "power forward"]),
    "Milan Sundström": ("Cerebral two-way C", ["A", "G", "Tk"], "2nd-line C",
                        "", "Son of Niklas Sundström. Point per game in Swedish U18 and U20. Classic Swedish two-way center, strong in Tk and Cor.", []),
    "Brock Cripps": ("Undersized offensive D", ["Pt-D", "A", "STP"], "2nd-pair offensive D",
                     "", "37 points as a WHL rookie plus 21 in 20 playoff games, and a shorthanded goal at the Hlinka. Mostly Pt-D value. Size may push him down draft boards.", []),
    "Yevgeni Yakunin": ("Big playmaking C", ["A", "Tk", "Cor"], "Middle-six C",
                        "", "About 50 points in the MHL. KHL contract with Spartak through 2031, so a long wait. Dynasty stash only.", ["KHL contract to 2031"]),
    "Andrei Pustovoy": ("Power scorer, one-timer", ["G", "SOG", "STP"], "Middle-six scoring W",
                        "", "32 goals and 62 points in the MHL; a late-2008 birthday. Heavy shot and a PP one-timer.", ["late birthday"]),
    "Levi Harper": ("Offensive D, lethal shot", ["Pt-D", "SOG", "STP"], "PP specialist D",
                    "", "57 points as an OHL rookie D. Shoots a lot, and the defense is still raw. A classic fantasy-over-real D.", []),
    "Boston Tait": ("Two-way D with physical edge", ["Blk", "Hit", "PIM", "Pt-D"], "2nd/3rd-pair D",
                    "", "23 points and 55 PIM on a bad Wenatchee team. Physical and gets pucks to the net. A banger-D profile that suits Hit/Blk/PIM.", ["banger"]),
    "Bosse Meijer": ("Small speedy playmaking C", ["A", "G", "SOG"], "Middle-six F",
                     "", "25 points in 13 U20 playoff games led the league. Viggo Björck-like profile. Could push up draft boards with SHL time.", ["riser"]),
    "Diego Gutierrez": ("Mobile puck-rushing D", ["Pt-D", "A", "Cor"], "2nd-pair D",
                        "", "NTDP defender built for the modern game: gap control and rushes. Pt-D and Corsi type.", []),
    "Vladimir Shtyrkhunov": ("Offensive D", ["Pt-D", "A"], "3rd-pair/PP D",
                             "", "32 MHL points at 16, now in the QMJHL (Shawinigan). Needs size.", []),
    "Nolan Fitzhenry": ("Chaos-thriving scoring C", ["G", "SOG"], "Middle-six F", "", "Electric with the NTDP U17 team and has a great shot.", []),
    "Rocco Pelosi": ("Speed C with a deadly release", ["G", "SOG"], "Middle-six F", "", "Younger brother of Chris Pelosi. Streaky but dangerous.", []),
    "Ryerson Edgar": ("Speedy, reliable two-way C", ["A", "Tk"], "Middle-six F", "", "Just under 50 points as an OHL rookie. Strong defensively for his age.", []),
    "Jamie Glance": ("Detail/forecheck winger, draws penalties", ["Tk", "Hit", "Cor"], "3rd-line W",
                     "", "Much of what he does doesn't show on the scoresheet: forces giveaways and draws penalties. THW calls him a sleeper. Tk-leaning fantasy fit.", ["sleeper"]),
    "Noah Davidson": ("6'3\" 216 lb power forward", ["G", "Hit", "SOG", "PIM"], "Middle-six power F",
                      "", "30 goals and 52 points as a WHL rookie. Big, physical scorer with a heavy shot and a Boston College commit. Strong Hit + G fantasy blend.", ["power forward"]),
    "James Scantlebury": ("Pure playmaker", ["A", "STP"], "Middle-six playmaker", "", "Some of the best playmaking in the class; joins QMJHL Quebec.", []),
    "Kohyn Eshkawkogan": ("Dynamic rush D", ["Pt-D", "A"], "2nd-pair D", "", "53 points in 68 OHL games; Penn State commit. Undersized.", ["NCAA commit"]),
    "Shaeffer Gordon-Carroll": ("Hard-working two-way W", ["Hit", "SOG"], "Depth-plus W", "", "Role expanding with the Ruck twins in Medicine Hat.", []),
    "Douglas Johnsson": ("Small elite-skating puck D", ["Pt-D", "A"], "Offensive 2nd-pair D", "", "Superb numbers at every Swedish level. Size is the question.", []),
    "Jaakko Wycisk": ("Physical forechecking C/W", ["Hit", "A", "Tk"], "Middle-six F", "", "43 points in 60 OHL games; one of Canada's most consistent players at the Hlinka.", []),
    "Kayden Stroeder": ("Tenacious all-round C", ["Tk", "Hit", "A"], "Middle-six F", "", "\"5-foot-10, 150 but played like 6-foot-2, 200\" (THW). A Hlinka x-factor.", []),
    "Gavin Burcar": ("Shot-volume C", ["SOG", "G"], "Middle-six F", "", "Consistent shot generator at the Hlinka. 7 goals and 17 points last season, so a big jump is expected.", []),
    "Malik L'Italien": ("Two-way D, gap control", ["Blk", "Pt-D"], "2nd/3rd-pair D", "", "QMJHL All-Rookie. Defensive-first with a good first pass.", []),
    "Tomas Selic": ("Big workhorse W", ["G", "Hit", "SOG"], "Middle-six W", "", "Slovakia's standout at the U18s and the Hlinka.", []),
    "Dorian Eklund Aspe": ("6'4\" heavy skill F", ["Hit", "G"], "Middle-six power F", "", "Imposing frame with skill and a burst of speed.", []),
    "Lukas Kachlir": ("Offensive D", ["Pt-D", "A"], "3rd-pair/PP D", "", "27 points in 29 Czech U20 games at 16.", []),
    "Roberts Naudins": ("6'7\" C/LW", ["Hit", "G"], "Project", "", "Huge frame; moved to the WHL's Penticton Vees.", ["project"]),
    "Johnny McLaughlin": ("C", ["A", "G"], "Middle-six F", "", "Windsor Spitfires center on THW's top 32.", []),
    "Lenni Kokkonen": ("Puck-moving D", ["Pt-D", "A"], "3rd-pair D", "", "Kärpät D, on DFO's also-considered list.", []),
    "Trevor Daley Jr.": ("Skilled W", ["A", "G"], "Middle-six W", "", "Son of Trevor Daley, Soo Greyhounds. On DFO's also-considered list.", []),
    "Michal Hartl": ("Scoring W", ["G", "SOG"], "Middle-six W", "", "Kometa Brno U20, on DFO's also-considered list.", []),
}

# ---------------------------------------------------------------- 2028 (born roughly Sep 16, 2009 - Sep 15, 2010)
B28_SOURCES = [
    {"name": "Daily Faceoff: 15 players to know (2028)", "url": "https://www.dailyfaceoff.com/news/2028-nhl-draft-maddox-schultz-among-15-players-you-need-to-know", "date": "2026-07"},
    {"name": "NHL.com: Schultz ahead of 2028 draft", "url": "https://www.nhl.com/news/topic/nhl-draft/maddox-schultz-has-big-footsteps-to-follow-ahead-of-2028-nhl-draft", "date": "2026-08-09"},
    {"name": "The Hockey Writers: Schultz on his way to 1st overall", "url": "https://thehockeywriters.com/maddox-schultz-is-on-his-way-to-1st-overall-in-the-2028-nhl-draft/", "date": "2026-08-08"},
    {"name": "WHL: 2025 Prospects Draft first round (2010-born)", "url": "https://chl.ca/whl/article/western-hockey-league-completes-first-round-of-2025-whl-prospects-draft/", "date": "2025-05"},
    {"name": "OHL: 2026 Priority Selection first round", "url": "https://chl.ca/ohl/article/2026-ohl-priority-selection-first-round-recap/", "date": "2026-06-13"},
    {"name": "QMJHL: 2026 draft first-round recap", "url": "https://chl.ca/lhjmq/en/article/2026-qmjhl-draft-recap-of-an-eventful-first-round/", "date": "2026-06"},
]
# rank, name, pos, team/league, stats dict or None, style, cats, ceiling, comp, note, sources(list of names), tags
B28 = [
    (1, "Maddox Schultz", "C", "Regina Pats (WHL)", {"season": "2025-26", "league": "WHL", "gp": 34, "g": 15, "a": 14, "pts": 29},
     "Complete 200-ft C: shoots, passes, hits", ["G", "A", "Hit", "2G+A"], "Franchise C", "Crosby (DuPont quote, NHL.com)",
     "Born Mar 15 2010. First overall in the 2025 WHL draft. 29 points in 34 WHL games at 15, the best by a 15-year-old forward in the 2000s (DFO), plus 60 points in 21 U18 AAA games. Led the 2026 Hlinka Gretzky Cup with 10 points in 5 games. Consensus early No. 1.", ["DFO", "NHL.com", "THW", "WHL"], ["early #1"]),
    (2, "Liam Pue", "RW", "Regina Pats (WHL)", {"season": "2025-26", "league": "WHL", "gp": 34, "g": 6, "a": 10, "pts": 16},
     "Elite-hands playmaker", ["A", "STP", "G"], "1st-line W", "", "No. 3 in the 2025 WHL draft. Schultz's linemate in Regina and at the Hlinka, with 9 points in 5 games there. Some of the best hands in the class (DFO).", ["DFO", "NHL.com", "WHL"], []),
    (3, "Matyáš Michálek", "LD", "Oshawa Generals (OHL)", None, "Mature 6'3\" two-way D", ["Blk", "Pt-D", "Cor"], "Top-pair D", "",
     "First pick in the 2026 CHL Import Draft. Star for Czechia at the U16 and U18 levels (DFO). Rarely makes mistakes under pressure.", ["DFO"], ["import"]),
    (4, "Joey Cullen", "LW", "USNTDP", None, "Fast, smart play-driving W", ["G", "A", "SOG"], "1st/2nd-line W", "",
     "Younger brother of Wyatt Cullen, the 2026 10th overall pick. 'Might be better' (DFO). Top NTDP U17 recruit.", ["DFO"], []),
    (5, "Paavo Fugleberg", "RW", "TPS U20 (Finland)", None, "Dynamic 1-on-1 skill W, reliable defensively", ["G", "A", "Tk"], "1st/2nd-line W", "",
     "Standout at the U17 World Challenge and the U18s, with excellent numbers against older U20 players (DFO).", ["DFO"], []),
    (6, "Kane Cloutier", "C", "Oshawa Generals (OHL)", {"season": "2025-26", "league": "GTHL U16", "gp": 33, "pts": 58},
     "Pace C, shooter + passer", ["G", "A", "SOG"], "2nd-line C", "", "First overall in the 2026 OHL draft (Jack Ferguson Award). Son of Dan Cloutier. 58 points in 33 GTHL games plus 11 in 4 at the OHL Cup (DFO).", ["DFO", "OHL"], []),
    (7, "Wilson Boumedienne", "C", "Fargo Force (USHL)", None, "High-end offensive instincts", ["G", "A", "SOG"], "2nd-line C", "",
     "Brother of Jets prospect Sascha Boumedienne. Dominated the Swedish U16 team and saw U18 action (DFO).", ["DFO"], []),
    (8, "Drew Daley", "RHD", "USNTDP", None, "Poised puck-moving D", ["Pt-D", "A", "Cor"], "Top-pair D", "",
     "One of Shattuck's top 18U players a year after playing 14U. \"Everything screams top-pairing D\" (DFO).", ["DFO"], []),
    (9, "Isak Alvudd", "LW", "HV71 (Sweden U18)", None, "Skilled, quick puck thief", ["Tk", "A", "G"], "2nd-line W", "",
     "Highlight moments at the April 4 Nations tournament. Equally good against older players (DFO).", ["DFO"], ["Tk profile"]),
    (10, "Zaac Charbonneau", "C", "Muskegon Lumberjacks (USHL)", None, "Goal-scoring two-way C, 6'1\" 185", ["G", "SOG", "Hit"], "2nd-line C", "",
     "Over a goal per game for Mount St. Charles 15U, with advanced hockey sense. Nephew of Danny Brière (DFO).", ["DFO"], []),
    (11, "Milo Spelkvist", "RW", "Örebro HK (Sweden U18)", None, "Shot-generation machine", ["SOG", "G"], "2nd-line W", "",
     "Electric at the 4 Nations tournament. Could be one of the first off the board (DFO).", ["DFO"], ["SOG"]),
    (12, "Adrian Sgro", "LHD", "Sarnia Sting (OHL)", None, "Physical, dynamic D", ["Hit", "Blk", "Pt-D"], "2nd-pair D", "",
     "No. 4 in the 2026 OHL draft. \"Hits everyone in sight\" while still rushing the puck (DFO). A banger-D fantasy profile.", ["DFO", "OHL"], ["banger"]),
    (13, "Louis-Oscar Holowaychuk", "C", "Vancouver Giants (WHL)", {"season": "2024-25", "league": "U15/Giants program", "gp": 34, "g": 50, "a": 33, "pts": 83},
     "High-IQ middle-of-the-ice C", ["A", "G"], "2nd-line C", "", "No. 6 in the 2025 WHL draft; stats are from the WHL draft release. Impressive in limited WHL action (DFO).", ["DFO", "WHL"], []),
    (14, "Gordei Khotkov", "LHD", "Saginaw Spirit (OHL)", None, "6'4\" mobile puck-moving D", ["Pt-D", "Blk"], "2nd-pair D", "",
     "CHL import selection. Productive at every Russian junior level (DFO).", ["DFO"], ["import"]),
    (15, "Lionel Dedial", "RW", "GCK Lions (Switzerland U21)", None, "Skill + muscle scorer", ["G", "SOG", "Hit"], "2nd-line W", "",
     "About 1.5 goals per game for the Swiss U16 team and well over 50 points across U18/U21. A late-2010 birthday (DFO).", ["DFO"], []),
    (16, "Holden Wouters", "D", "Edmonton Oil Kings (WHL)", {"season": "2024-25", "league": "U15 Prep", "gp": 29, "g": 12, "a": 29, "pts": 41},
     "Puck-moving D", ["Pt-D", "A"], "2nd-pair D", "", "No. 2 in the 2025 WHL draft (stats from the WHL draft release).", ["WHL"], []),
    (17, "Colin Kennedy", "C", "Erie Otters (OHL)", None, "Skilled C (5'9\")", ["A", "G"], "Middle-six C", "", "No. 2 in the 2026 OHL draft (Detroit Little Caesars).", ["OHL"], []),
    (18, "Tanner Adams", "C", "Brampton Steelheads (OHL)", None, "C", ["A", "G"], "Middle-six C", "", "No. 3 in the 2026 OHL draft (Hill Academy).", ["OHL"], []),
    (19, "Thomas Boisvert", "C", "Rouyn-Noranda Huskies (QMJHL)", None, "Dynamic distributing C", ["A", "STP"], "Middle-six C", "",
     "First overall in the 2026 QMJHL draft. Top prospect per QMJHL Central Scouting (Mount St. Charles).", ["QMJHL"], []),
    (20, "Benjamin Veitch", "F", "Canada U18 (Hlinka)", None, "Physical third-line energy", ["Hit", "Tk"], "Middle-six F", "",
     "2028-eligible forward on Canada's dominant Hlinka third line (THW).", ["THW"], []),
    (21, "Thor Liffiton", "D", "WHL (Penticton pick)", {"season": "2024-25", "league": "U15 AAA", "gp": 32, "g": 7, "a": 31, "pts": 38}, "Puck-moving D", ["Pt-D", "A"], "Middle-pair D", "", "No. 4 in the 2025 WHL draft.", ["WHL"], []),
    (22, "Reid Nicol", "C", "Everett Silvertips (WHL)", {"season": "2024-25", "league": "U18 AAA", "gp": 48, "g": 35, "a": 23, "pts": 58}, "Scoring C", ["G", "SOG"], "Middle-six C", "", "No. 5 in the 2025 WHL draft; 35 goals in U18 AAA at 14-15.", ["WHL"], []),
    (23, "Vincent Boutet", "D", "Victoriaville Tigres (QMJHL)", None, "Physical, composed 6'1\" D", ["Hit", "Blk"], "Middle-pair D", "", "No. 2 in the 2026 QMJHL draft; top blueliner available.", ["QMJHL"], []),
    (24, "Jacob McKinnon", "F", "Blainville-Boisbriand Armada (QMJHL)", None, "Shooter-passer with hockey sense", ["G", "A"], "Middle-six F", "", "No. 3 in the 2026 QMJHL draft.", ["QMJHL"], []),
    (25, "Kash Kwajah", "C", "Sudbury Wolves (OHL)", None, "C", ["A", "G"], "Middle-six F", "", "No. 5 in the 2026 OHL draft.", ["OHL"], []),
    (26, "Drew Bate", "C", "Saginaw Spirit (OHL)", None, "C", ["A", "G"], "Middle-six F", "", "No. 6 in the 2026 OHL draft.", ["OHL"], []),
    (27, "Declan McNally", "LD", "Guelph Storm (OHL)", None, "6'6\" D", ["Blk", "Hit"], "Shutdown D", "", "No. 7 in the 2026 OHL draft.", ["OHL"], ["size"]),
    (28, "Nolan Wolitski", "D", "Red Deer Rebels (WHL)", {"season": "2024-25", "league": "U15 Prep", "gp": 29, "g": 8, "a": 40, "pts": 48}, "Playmaking D", ["Pt-D", "A"], "Middle-pair D", "", "No. 7 in the 2025 WHL draft.", ["WHL"], []),
    (29, "Ben Oliverio", "C", "Tri-City Americans (WHL)", {"season": "2024-25", "league": "U15 AAA", "gp": 28, "g": 37, "a": 40, "pts": 77}, "Scoring C", ["G", "A"], "Middle-six C", "", "No. 9 in the 2025 WHL draft.", ["WHL"], []),
    (30, "Logan Prud'homme", "C", "Kingston Frontenacs (OHL)", None, "6'7\" C", ["Hit", "G"], "Project", "", "No. 10 in the 2026 OHL draft.", ["OHL"], ["size"]),
    (31, "Matteo Ferreira", "D", "Kamloops Blazers (WHL)", {"season": "2024-25", "league": "U15 AAA", "gp": 32, "g": 21, "a": 49, "pts": 70}, "Offensive D", ["Pt-D", "A"], "Offensive D", "", "No. 11 in the 2025 WHL draft; 70 points as a U15 D.", ["WHL"], []),
    (32, "Owen Loftus", "G", "North Bay Battalion (OHL)", None, "Goalie", ["SV%", "W"], "Starter candidate", "", "First goalie taken in the 2026 OHL draft (11th overall).", ["OHL"], ["goalie"]),
]

# ---------------------------------------------------------------- 2029 (born roughly Sep 16, 2010 - Sep 15, 2011)
B29_SOURCES = [
    {"name": "WHL: 2026 Prospects Draft first round (2011-born)", "url": "https://chl.ca/whl/article/western-hockey-league-completes-first-round-of-2026-whl-prospects-draft/", "date": "2026-05-07"},
    {"name": "The Hockey News: Next In Line (Daneault)", "url": "https://thehockeynews.com/news/latest-news/next-in-line-a-sneak-peak-at-one-of-the-top-2029-draft-eligible-prospects", "date": "2026-07-05"},
    {"name": "Black Stitch Hockey: Who is Madden Daneault?", "url": "https://blackstitchhockey.com/2026/07/20/prospects-to-know-who-is-madden-daneault/", "date": "2026-07-20"},
    {"name": "Daily Faceoff: Kade O'Rourke exceptional status", "url": "https://www.dailyfaceoff.com/news/kade-o-rourke-scouting-report-ohl-exceptional-status-2029-nhl-draft", "date": "2026-04"},
]
B29 = [
    (1, "Madden Daneault", "C", "Kelowna Rockets (WHL) / Red Deer U18", {"season": "2025-26", "league": "U15 AAA", "gp": 34, "g": 65, "a": 84, "pts": 149},
     "Franchise-type C who runs the offense", ["G", "A", "2G+A", "STP"], "Franchise C", "",
     "Born May 7 2011. First overall in the 2026 WHL draft. 149 points in 34 U15 AAA games; the next-best teammate had 65 (THN). Two-time John Reid Memorial MVP. EliteProspects' Cam Robinson reportedly projects him as the 2029 No. 1.", ["WHL", "THN", "Black Stitch", "DFO"], ["early #1"]),
    (2, "Kade O'Rourke", "RHD", "OHL (exceptional status)", None, "Mobile PP quarterback D, 6'1\"", ["Pt-D", "A", "STP", "Cor"], "Top-pair D", "",
     "Born Jan 31 2011. Granted OHL exceptional status, the first American and the first since Michael Misa. 10 points in 6 OHL Cup games. \"Most dangerous on the power play\" (DFO). Ideal fantasy-D traits.", ["DFO"], ["exceptional status"]),
    (3, "Parker McMillan", "RW", "Wenatchee Wild (WHL)", None, "Scoring W", ["G", "SOG"], "Top-six W", "", "No. 2 in the 2026 WHL draft (Wenatchee traded up for him).", ["WHL"], []),
    (4, "Brayden Jugnauth", "C", "Vancouver Giants (WHL)", None, "C", ["A", "G"], "Top-six C", "", "No. 4 in the 2026 WHL draft; already at the U18 AAA level (Okanagan Rockets).", ["WHL"], []),
    (5, "Eli Vickers", "D", "Vancouver Giants (WHL)", None, "D", ["Pt-D", "Blk"], "Top-four D", "", "No. 3 in the 2026 WHL draft.", ["WHL"], []),
    (6, "Jevin Morrison", "D", "Wenatchee Wild (WHL)", None, "D", ["Pt-D", "Blk"], "Top-four D", "", "No. 5 in the 2026 WHL draft; Daneault's Red Deer teammate.", ["WHL"], []),
    (7, "Kenzo Gibson", "C", "Tri-City Americans (WHL)", None, "C", ["A", "G"], "Middle-six C", "", "No. 6 in the 2026 WHL draft.", ["WHL"], []),
    (8, "Wyatt Jolleys", "C", "Seattle Thunderbirds (WHL)", None, "C", ["A", "G"], "Middle-six C", "", "No. 7 in the 2026 WHL draft.", ["WHL"], []),
    (9, "Micah Montgomery", "C", "Kamloops Blazers (WHL)", None, "C", ["A", "G"], "Middle-six C", "", "No. 8 in the 2026 WHL draft.", ["WHL"], []),
    (10, "Fletcher MacDonald", "G", "Regina Pats (WHL)", None, "Goalie", ["SV%", "W"], "Starter candidate", "", "No. 9 in the 2026 WHL draft; the first goalie taken.", ["WHL"], ["goalie"]),
    (11, "Cullen Stephenson", "RW", "Portland Winterhawks (WHL)", None, "W", ["G", "SOG"], "Middle-six W", "", "No. 10 in the 2026 WHL draft.", ["WHL"], []),
    (12, "Jax Bubnick", "D", "Seattle Thunderbirds (WHL)", None, "D", ["Blk", "Pt-D"], "Middle-pair D", "", "No. 11 in the 2026 WHL draft.", ["WHL"], []),
    (13, "Brody Antignani", "RW", "Spokane Chiefs (WHL)", None, "W", ["G", "SOG"], "Middle-six W", "", "No. 12 in the 2026 WHL draft.", ["WHL"], []),
    (14, "Wyatt Bitz", "D", "Everett Silvertips (WHL)", None, "D", ["Blk", "Pt-D"], "Middle-pair D", "", "No. 13 in the 2026 WHL draft.", ["WHL"], []),
    (15, "Artello Forestal", "C", "Lethbridge Hurricanes (WHL)", None, "C", ["A", "G"], "Middle-six C", "", "No. 14 in the 2026 WHL draft.", ["WHL"], []),
    (16, "Teagan Dernisky", "C", "Saskatoon Blades (WHL)", None, "C", ["A", "G"], "Middle-six C", "", "No. 15 in the 2026 WHL draft.", ["WHL"], []),
    (17, "Jack Arnold", "RW", "Spokane Chiefs (WHL)", None, "W", ["G"], "Middle-six W", "", "No. 16 in the 2026 WHL draft (Dallas Stars Elite, Texas).", ["WHL"], []),
    (18, "Danny Ramazanov", "LW", "Red Deer Rebels (WHL)", None, "W", ["G"], "Middle-six W", "", "No. 17 in the 2026 WHL draft.", ["WHL"], []),
    (19, "Rylan Edwards", "C", "Brandon Wheat Kings (WHL)", None, "C", ["A"], "Middle-six C", "", "No. 18 in the 2026 WHL draft.", ["WHL"], []),
    (20, "Max Osgood", "C", "Medicine Hat Tigers (WHL)", None, "C", ["A", "G"], "Middle-six C", "", "No. 21 in the 2026 WHL draft (Detroit Little Caesars 14U).", ["WHL"], []),
]
